[build]
  publish = "demo/storybook-static/"
  command = "yarn build && cd demo && yarn && yarn build-storybook"

[context.branch-deploy]
  publish = "demo/storybook-static/"
  command = "yarn build && cd demo && yarn install && yarn build-storybook"
