[build]
  publish = "demo/storybook-static/"
  command = "npm run build && cd demo && npm install && npm run build-storybook"

[context.branch-deploy]
  publish = "demo/storybook-static/"
  command = "npm run build && cd demo && npm install && npm run build-storybook"
